CREATE TABLE QUIZ (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE STUDENTS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  student_number INT UNIQUE NOT NULL,
  name VARCHAR(64) NOT NULL,
  surname VARCHAR(64) NOT NULL,
  quiz_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (quiz_id) REFERENCES QUIZ (id)
);

CREATE TABLE QUESTIONS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  question_text TEXT NOT NULL,
  quiz_id INT NOT NULL,
  FOREIGN KEY (quiz_id) REFERENCES QUIZ (id)
);

CREATE TABLE ANSWERS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  question_id INT NOT NULL,
  student_id INT NULL,
  answer_text TEXT NOT NULL,
  is_correct BOOLEAN NOT NULL,
  FOREIGN KEY (question_id) REFERENCES QUESTIONS (id),
  FOREIGN KEY (student_id) REFERENCES STUDENTS (id)
);

CREATE TABLE ADMIN (
  id INT PRIMARY KEY AUTO_INCREMENT,
  code INT NOT NULL
);

INSERT INTO ADMIN (code) VALUES (1024);
INSERT INTO ADMIN (code) VALUES (2048);

